name: Linux

on:
  push:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build
    ## using self-hosted b/c can't get ubuntu-latest to work (needs GCC 15 and maybe Ubuntu 25.04)
    runs-on: self-hosted

    steps:
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get -y install \
          build-essential \
          cmake \
          qt6-base-dev \
          qt6-svg-dev

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: true

      - name: Config
        run: cmake -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build build --target surkl --parallel

      - name: Strip Symbols
        run: |
          cd build
          strip surkl

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: "surkl-x86_64"
          path: build/surkl
